name: build & deploy
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  # AWS_REGION: us-west-1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/iron]

    steps:
      - uses: actions/checkout@v3

      - name: install node modules
        run: |
          npm ci

      - name: build
        run: |
          npm run build

      - name: unit test
        run: |
          npm run test

      - name: e2e test
        run: |
          npm run wdio
